ARG REL_VER

FROM scratch AS ctx
COPY ctx /

FROM quay.io/fedora/fedora-bootc:${REL_VER} AS builder

ARG REL_VER
ENV REL_VER=${REL_VER}

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    /ctx/base/rootfs.sh

FROM scratch
COPY --from=builder /target-rootfs/ /

RUN bootc container lint --no-truncate

LABEL containers.bootc 1

ENV container=oci
STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]
