name: Reusable bootable containers image builder

on:
  workflow_call:
    inputs:
      containerfile:
        required: true
        type: string

      image_tag:
        required: true
        type: string

      base_image:
        required: false
        type: string
        default: ""

      Image_title:
        required: false
        type: string
        default: "Asahi Remix Atomic Image"

      image_description:
        required: false
        type: string
        default: "Asahi Remix Atomic Image"

      rel_ver:
        required: false
        type: string
        default: "44"

      release:
        required: false
        type: boolean
        default: false

    secrets:
      COSIGN_PRIVATE_KEY:
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-26.04-arm
    timeout-minutes: 60
    # container:
    #   image: quay.io/podman/stable:v5
    #   options: "--security-opt apparmor=unconfined --security-opt label=disable --privileged --user root --device /dev/fuse -v /:/run/host:rw -v /var/tmp:/var/tmp -v /tmp:/tmp"

    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Checkout
        uses: actions/checkout@v7

      - name: Prepare env
        run: |
          if [[ "${{ github.event_name }}" == "schedule" || "${{ inputs.release }}" == "true" ]]; then
            IMG_VER="${{ inputs.rel_ver }}.$(date -u +%Y%m%d).0"
            IS_RELEASE=true
          else
            IMG_VER="${GITHUB_SHA:0:7}"
            IS_RELEASE=false
          fi

          echo "IMG_VER=${IMG_VER}" >> $GITHUB_ENV
          echo "IMG_DT=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          echo "IS_RELEASE=${IS_RELEASE}" >> $GITHUB_ENV
          echo "BUILD_DIR=$(pwd)" >> $GITHUB_ENV

          # sed -i 's/driver = "overlay"/driver = "vfs"/' /usr/share/containers/storage.conf

      - name: Login registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} \
            --username ${{ github.actor }} \
            --password-stdin \
            --authfile /tmp/config.json

      - name: Build image
        run: |
          podman build \
            --format oci \
            --authfile /tmp/config.json \
            --tag ${IMAGE_NAME}:prechunk \
            --file ${{ inputs.containerfile }} \
            --build-arg REL_VER="${{ inputs.rel_ver }}" \
            --build-arg BASE_IMAGE="${{ inputs.base_image }}" \
            --label containers.bootc=1 \
            --label org.opencontainers.image.version="${IMG_VER}" \
            --label org.opencontainers.image.title="${{ inputs.image_title }}" \
            --label org.opencontainers.image.description="${{ inputs.image_description }}" \
            --label org.opencontainers.image.created="${IMG_DT}" \
            --annotation containers.bootc=1 \
            --annotation org.opencontainers.image.version="${IMG_VER}" \
            --annotation org.opencontainers.image.title="${{ inputs.image_title }}" \
            --annotation org.opencontainers.image.description="${{ inputs.image_description }}" \
            --annotation org.opencontainers.image.created="${IMG_DT}" \
            --cap-add=all \
            --device=/dev/fuse \
            --security-opt=label=disable \
            ${BUILD_DIR}

      - name: Chunk image
        run: |
          IMAGE_REF="localhost/${IMAGE_NAME}:prechunk"

          podman inspect "${IMAGE_REF}" > config_ref.json

          mkdir -p out

          podman run --rm \
            "--mount=type=image,src=${IMAGE_REF},target=/chunkah" \
            -v "${BUILD_DIR}/config_ref.json:/config_ref.json" \
            -v "${BUILD_DIR}/out:/run/out" \
            quay.io/coreos/chunkah:latest build \
              --verbose \
              --max-layers 128 \
              --config /config_ref.json \
              --tag "${IMAGE_NAME}:${{ inputs.image_tag }}" \
              --output oci:/run/out/chunked

      - name: Push image
        run: |
          if [[ "${IS_RELEASE}" == "true" ]]; then
            TAG="${{ inputs.image_tag }}"
          else
            TAG="${{ inputs.image_tag }}-ci"
          fi

          echo "IMG_TAG=${TAG}" >> $GITHUB_ENV

          skopeo copy \
            --authfile /tmp/config.json \
            --retry-times 3 \
            --dest-compress-format zstd \
            oci:${BUILD_DIR}/out/chunked \
            docker://${REGISTRY}/${IMAGE_NAME}:${TAG}

          skopeo copy \
            --authfile /tmp/config.json \
            --retry-times 3 \
            --dest-compress-format zstd \
            docker://${REGISTRY}/${IMAGE_NAME}:${TAG} \
            docker://${REGISTRY}/${IMAGE_NAME}:${TAG}.${IMG_VER}

      - name: Sign image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: |
          DIGEST=$(skopeo inspect \
            --authfile /tmp/config.json \
            --format '{{.Digest}}' \
            docker://${REGISTRY}/${IMAGE_NAME}:${IMG_TAG}.${IMG_VER})
          echo "IMG_DIGEST=${DIGEST}" >> $GITHUB_ENV

          export DOCKER_CONFIG=/tmp
          cosign sign \
            --yes \
            --key env://COSIGN_PRIVATE_KEY \
            ${REGISTRY}/${IMAGE_NAME}@${DIGEST}

      - name: Verify image signature
        run: |
          export DOCKER_CONFIG=/tmp
          cosign verify \
            --key "${BUILD_DIR}/cosign.pub" \
            ${REGISTRY}/${IMAGE_NAME}@${IMG_DIGEST}
