name: Build base image

on:
  push:
    branches:
      - main
    paths:
      - 'Containerfile.base'
      - '.github/workflows/build-base.yml'
      - 'build_files/base-build.sh'
      - 'build_files/base-packages.txt'
      - 'build_files/base-postprocess.sh'
      - 'build_files/base-rootfs/**'

  # schedule:
  #   - cron: "21 0 * * *"

  workflow_dispatch:
    inputs:
      release:
        description: "Publish as a release"
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:

  base:

    uses: ./.github/workflows/bootable-containers.yml

    with:

      containerfile: Containerfile.base

      image_tag: base

      release: ${{ (github.event_name == 'workflow_dispatch' && inputs.release) || false }}

    secrets: inherit
