name: Build WMX image


on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Containerfile.base'
      - '.github/workflows/build-base.yml'
      - 'ctx/base/**'
      - '**.md'
      - '.gitignore'

  # schedule:
  #   - cron: "32 1 * * *"

  workflow_dispatch:
    inputs:
      release:
        description: "Publish as a release"
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:

  wmx:

    uses: ./.github/workflows/bootable-containers.yml


    with:

      containerfile: Containerfile

      image_tag: wmx

      base_image: ghcr.io/${{ github.repository }}:base

      release: ${{ (github.event_name == 'workflow_dispatch' && inputs.release) || false }}

    secrets: inherit
