name: Cleanup

on:
  # schedule:
  #   - cron: "12 3 * * *"

  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run"
        type: boolean
        default: true

jobs:
  cleanup-images:
    runs-on: ubuntu-26.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Delete old container images
        uses: snok/container-retention-policy@v3.1.0
        with:
          account: user
          token: ${{ secrets.PKG }}
          image-names: ${{ github.event.repository.name }}
          image-tags: "!wmx !base"
          cut-off: 4w
          keep-n-most-recent: 5
          dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || false }}

  cleanup-actions:
    runs-on: ubuntu-26.04
    permissions:
      actions: write
      contents: read

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          dry_run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || false }}
